image: nginx:alpine

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp index.html .public/
    - cp index.css .public/
    - cp index.js .public/
  artifacts:
    paths:
      - public
  only:
    - master
